name: Deploy website to gh-pages branch

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout full repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Build the website
      run: |
        sudo snap install hugo
        hugo
      working-directory: hugo_site

    - name: Deploy contents of `hugo_site/public` to gh-pages docs dir
      run: |
        git config user.name "github-action"
        git config user.email "github-action"
        git checkout gh-pages
        rm -rf docs/*
        cp -rT hugo_site docs
        git add --all
        git commit -m "deploy website" || echo "No changes to commit"
        git push
